name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
  pull_request:

env:
  NODE_VERSION: 10
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}
  PERCY_PARALLEL_TOTAL: 1
  FORCE_COLOR: 1

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run lint

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@7
      - run: npm install --no-package-lock
      - run: npm test

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ee0a9d5c1122d6a21852edf19b5b309aaec18077fb3900c98995c90bc48ed240
      RUN_PERCY_TESTS: true


    steps:
      - uses: actions/checkout@v2
      - uses: mansona/npm-lockfile-version@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@7
      - run: npm ci
      - run: npx percy exec -- npm run test

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    strategy:
      matrix:
        ember-try-scenario:
          - 'ember-lts-3.16'
          - 'ember-lts-3.20'
          - 'ember-lts-3.24'
          - 'ember-release'
          - 'ember-beta'
          - 'ember-canary'
          - 'ember-default-with-jquery'
          - 'ember-classic'
          - 'embroider-safe'
          - 'embroider-optimized'
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@7
      - run: npm ci
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
